package com.oliwer.plantswap.enums;

public enum StageOfGrowth {
    GERMINATION, LEAFDEVELOPMENT, FORMATIONOFSIDESHOOTS, STEMELONGATION, VEGETATIVEPLANTPARTS, INFLORESCENCEEMERGEGENCE,
    FLOWERING, FRUITDEVELOPMENT, RIPENING, SENESCENCE;






}
